/*
 * Generate a quote for the day
 *
 * Copyright (c) Nostrium contributors
 * License: Apache-2.0
 */

package online.nostrium.servers.qoft;

import java.util.Random;

/**
 * @author Brito
 * @date: 2024-08-31
 * @location: Germany
 */
public class QOTD {

    private static final String[] PART_ONE = {
        "Decentralize your systems", 
        "Encrypt your communications", 
        "Store data on-chain", 
        "Adopt zero-knowledge proofs", 
        "Use end-to-end encryption", 
        "Build with open-source tools", 
        "Audit your code", 
        "Use decentralized identity", 
        "Control your private keys", 
        "Implement decentralized governance", 
        "Utilize multi-signature wallets", 
        "Opt for peer-to-peer transactions", 
        "Ensure data sovereignty", 
        "Embrace distributed ledgers", 
        "Prioritize user anonymity", 
        "Adopt privacy-preserving technologies", 
        "Invest in cryptographic research", 
        "Trust the code, not intermediaries", 
        "Enable permissionless innovation", 
        "Focus on security-first development ",
        "Live off-grid", 
        "Harvest your own energy", 
        "Grow your own food", 
        "Embrace self-sufficiency", 
        "Reconnect with nature", 
        "Simplify your life", 
        "Reduce your dependence", 
        "Protect your privacy", 
        "Value your freedom", 
        "Advocate for human rights", 
        "Fight for digital freedom", 
        "Defend cybersecurity", 
        "Embrace open source", 
        "Seek alternative energies", 
        "Pursue sustainable living", 
        "Champion privacy laws", 
        "Guard your personal data", 
        "Resist surveillance", 
        "Cultivate resilience", 
        "Practice mindful living", 
        "Prioritize mental health", 
        "Opt for renewable resources", 
        "Live minimally", 
        "Adopt a low-tech lifestyle", 
        "Cherish community", 
        "Engage in local governance", 
        "Support decentralized networks", 
        "Uphold digital rights", 
        "Reject corporate control", 
        "Be your own master", 
        "Embrace freedom of thought", 
        "Defend the right to privacy", 
        "Guard against digital threats", 
        "Value human dignity", 
        "Create a self-reliant life", 
        "Live closer to the land", 
        "Empower yourself through technology", 
        "Seek balance between tech and nature", 
        "Protect the environment"
    };

    private static final String[] PART_TWO = {
        "to eliminate centralized points of failure.", 
        "to protect against surveillance.", 
        "to ensure data immutability.", 
        "to provide privacy without trust.", 
        "to secure your digital life.", 
        "for transparent control.", 
        "to prevent vulnerabilities.", 
        "for self-sovereign identities.", 
        "to make decisions collectively.", 
        "for secure asset management.", 
        "to cut out the middlemen.", 
        "to retain control over your data.", 
        "for resilient record-keeping.", 
        "in every digital interaction.", 
        "to protect personal information.", 
        "for future-proof privacy.", 
        "to overcome the gatekeepers.", 
        "to empower creators globally.", 
        "to safeguard against cyber threats.",
        "to reduce reliance on the grid.", 
        "to reclaim your independence.", 
        "to foster community resilience.", 
        "to live sustainably.", 
        "to minimize your carbon footprint.", 
        "to achieve true freedom.", 
        "to simplify your life.", 
        "to connect with the earth.", 
        "to protect natural resources.", 
        "to live authentically.", 
        "to defend the vulnerable.", 
        "to uphold justice.", 
        "to resist digital colonization.", 
        "to decentralize power structures.", 
        "to ensure lasting security.", 
        "to champion the disenfranchised.", 
        "to preserve civil liberties.", 
        "to promote global equality.", 
        "to secure the future of the internet.", 
        "to challenge corporate hegemony.", 
        "to foster human connection.", 
        "to nurture creativity.", 
        "to build resilient communities.", 
        "to align with your values.", 
        "to avoid technological dependence.", 
        "to honor your ancestors.", 
        "to protect your legacy.", 
        "to support local economies.", 
        "to live within your means.", 
        "to focus on what truly matters.", 
        "to disconnect from the noise.", 
        "to preserve your mental clarity.", 
        "to enrich your soul.", 
        "to live in harmony with nature.", 
        "to find peace in simplicity.", 
        "to be the change you wish to see."
    };

    private static final String[] PART_THREE = {
        "Decentralization isn't optional; it's necessary.", 
        "Your privacy is your freedom, guard it.", 
        "Control your data, or someone else will.", 
        "Cryptography is your shield in the digital age.", 
        "Centralization is a weakness, not a strength.", 
        "Trustlessness is the path to security.", 
        "Privacy is not a privilege; it's a right.", 
        "Decentralized systems are resilient by design.", 
        "Ownership is power; never give it away.", 
        "Without privacy, there is no freedom.", 
        "Security is not a product, it's a process.", 
        "Autonomy begins with decentralized tools.", 
        "Surveillance is a threat; encryption is the answer.", 
        "Digital rights are human rights.", 
        "In the digital world, privacy equals power.", 
        "A decentralized future is a secure future.", 
        "Take control of your digital destiny.", 
        "Empower yourself with technology, not corporations.", 
        "Decentralize or be compromised.", 
        "Either the future is encrypted, or it isn't free.",
        "Living off-grid is living on your own terms.", 
        "Simplicity is the ultimate sophistication.", 
        "True freedom is living sustainably.", 
        "Your energy is your independence.", 
        "Grow your own food, grow your own freedom.", 
        "Nature is the best teacher.", 
        "Reconnect with the earth, reclaim your peace.", 
        "In nature, we find our true selves.", 
        "Privacy is the key to a free society.", 
        "Digital freedom is a fundamental right.", 
        "Security in the digital age starts with you.", 
        "Off-grid living is the path to resilience.", 
        "Decentralization is the future of freedom.", 
        "The first step to freedom is to disconnect.", 
        "Human rights are non-negotiable.", 
        "Your data, your rules.", 
        "Decentralized networks are the backbone of a free internet.", 
        "To be off-grid is to be self-reliant.", 
        "Cybersecurity is the new frontier of human rights.", 
        "Protect nature, protect your future.", 
        "Freedom begins when dependency ends.", 
        "Embrace privacy, embrace freedom.", 
        "Decentralized systems empower individuals.", 
        "Sustainable living is true living.", 
        "Off-grid living: a journey back to basics.", 
        "The future is decentralized and secure.", 
        "Your privacy, your power.", 
        "Freedom is in the choices we make.", 
        "A decentralized world is a free world.", 
        "In nature, we find our balance.", 
        "Human rights are the foundation of civilization.", 
        "Off-grid is the new luxury.", 
        "Living minimally is living freely.", 
        "Cybersecurity is the shield of freedom."
    };

    public static String generateQuote() {
        Random random = new Random();

        String part1 = PART_ONE[random.nextInt(PART_ONE.length)];
        String part2 = PART_TWO[random.nextInt(PART_TWO.length)];
        String part3 = PART_THREE[random.nextInt(PART_THREE.length)];

        return String.format("%s %s %s", part1, part2, part3);
    }
}
